spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cashback_system
    username: root
    password: Jai@12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8088
